package test.model;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Authority.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Authority.name
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Authority.id
     *
     * @return the value of Authority.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Authority.id
     *
     * @param id the value for Authority.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Authority.name
     *
     * @return the value of Authority.name
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Authority.name
     *
     * @param name the value for Authority.name
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}