package test.model;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.commentSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Integer commentsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.createTime
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.readSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Integer readsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.summary
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.tags
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.title
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.voteSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Integer votesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.catalog_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.content
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.htmlContent
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String htmlcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.id
     *
     * @return the value of Blog.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.id
     *
     * @param id the value for Blog.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.commentSize
     *
     * @return the value of Blog.commentSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Integer getCommentsize() {
        return commentsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.commentSize
     *
     * @param commentsize the value for Blog.commentSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setCommentsize(Integer commentsize) {
        this.commentsize = commentsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.createTime
     *
     * @return the value of Blog.createTime
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.createTime
     *
     * @param createtime the value for Blog.createTime
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.readSize
     *
     * @return the value of Blog.readSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Integer getReadsize() {
        return readsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.readSize
     *
     * @param readsize the value for Blog.readSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setReadsize(Integer readsize) {
        this.readsize = readsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.summary
     *
     * @return the value of Blog.summary
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.summary
     *
     * @param summary the value for Blog.summary
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.tags
     *
     * @return the value of Blog.tags
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.tags
     *
     * @param tags the value for Blog.tags
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.title
     *
     * @return the value of Blog.title
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.title
     *
     * @param title the value for Blog.title
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.voteSize
     *
     * @return the value of Blog.voteSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Integer getVotesize() {
        return votesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.voteSize
     *
     * @param votesize the value for Blog.voteSize
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setVotesize(Integer votesize) {
        this.votesize = votesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.catalog_id
     *
     * @return the value of Blog.catalog_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.catalog_id
     *
     * @param catalogId the value for Blog.catalog_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.user_id
     *
     * @return the value of Blog.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.user_id
     *
     * @param userId the value for Blog.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.content
     *
     * @return the value of Blog.content
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.content
     *
     * @param content the value for Blog.content
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.htmlContent
     *
     * @return the value of Blog.htmlContent
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getHtmlcontent() {
        return htmlcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.htmlContent
     *
     * @param htmlcontent the value for Blog.htmlContent
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setHtmlcontent(String htmlcontent) {
        this.htmlcontent = htmlcontent == null ? null : htmlcontent.trim();
    }
}