package test.model;

public class BlogComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.blog_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.blog_id
     *
     * @return the value of blog_comment.blog_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.blog_id
     *
     * @param blogId the value for blog_comment.blog_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_id
     *
     * @return the value of blog_comment.comment_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_id
     *
     * @param commentId the value for blog_comment.comment_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
}