package test.model;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comment.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comment.content
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comment.createTime
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comment.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comment.id
     *
     * @return the value of Comment.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comment.id
     *
     * @param id the value for Comment.id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comment.content
     *
     * @return the value of Comment.content
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comment.content
     *
     * @param content the value for Comment.content
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comment.createTime
     *
     * @return the value of Comment.createTime
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comment.createTime
     *
     * @param createtime the value for Comment.createTime
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comment.user_id
     *
     * @return the value of Comment.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comment.user_id
     *
     * @param userId the value for Comment.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}