package test.model;

public class PageDemo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_demo.c1
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Integer c1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_demo.c2
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Integer c2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_demo.c3
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private String c3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_demo.c1
     *
     * @return the value of page_demo.c1
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Integer getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_demo.c1
     *
     * @param c1 the value for page_demo.c1
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setC1(Integer c1) {
        this.c1 = c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_demo.c2
     *
     * @return the value of page_demo.c2
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Integer getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_demo.c2
     *
     * @param c2 the value for page_demo.c2
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setC2(Integer c2) {
        this.c2 = c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_demo.c3
     *
     * @return the value of page_demo.c3
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public String getC3() {
        return c3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_demo.c3
     *
     * @param c3 the value for page_demo.c3
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setC3(String c3) {
        this.c3 = c3 == null ? null : c3.trim();
    }
}