package test.model;

public class UserAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authority.authority_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    private Long authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.user_id
     *
     * @return the value of user_authority.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.user_id
     *
     * @param userId the value for user_authority.user_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authority.authority_id
     *
     * @return the value of user_authority.authority_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public Long getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authority.authority_id
     *
     * @param authorityId the value for user_authority.authority_id
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    public void setAuthorityId(Long authorityId) {
        this.authorityId = authorityId;
    }
}