package com.davin.miaoshaproject.dao;

import com.davin.miaoshaproject.model.SequenceInfo;
import com.davin.miaoshaproject.model.SequenceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    long countByExample(SequenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int deleteByExample(SequenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int insert(SequenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int insertSelective(SequenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    List<SequenceInfo> selectByExample(SequenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    SequenceInfo selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") SequenceInfo record, @Param("example") SequenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int updateByExample(@Param("record") SequenceInfo record, @Param("example") SequenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Oct 16 14:49:47 CST 2019
     */
    int updateByPrimaryKey(SequenceInfo record);
}