package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Authority;
import test.model.AuthorityExample;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    long countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    List<Authority> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    Authority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByPrimaryKey(Authority record);
}