package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.BlogVote;
import test.model.BlogVoteExample;

public interface BlogVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    long countByExample(BlogVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int deleteByExample(BlogVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insert(BlogVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insertSelective(BlogVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    List<BlogVote> selectByExample(BlogVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") BlogVote record, @Param("example") BlogVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_vote
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExample(@Param("record") BlogVote record, @Param("example") BlogVoteExample example);
}