package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.PageDemo;
import test.model.PageDemoExample;

public interface PageDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    long countByExample(PageDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int deleteByExample(PageDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int deleteByPrimaryKey(Integer c1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insert(PageDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insertSelective(PageDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    List<PageDemo> selectByExample(PageDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    PageDemo selectByPrimaryKey(Integer c1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") PageDemo record, @Param("example") PageDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExample(@Param("record") PageDemo record, @Param("example") PageDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByPrimaryKeySelective(PageDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_demo
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByPrimaryKey(PageDemo record);
}