package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.UserAuthority;
import test.model.UserAuthorityExample;

public interface UserAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    long countByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int deleteByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insert(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int insertSelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    List<UserAuthority> selectByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAuthority record, @Param("example") UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbg.generated Fri Oct 11 10:29:56 CST 2019
     */
    int updateByExample(@Param("record") UserAuthority record, @Param("example") UserAuthorityExample example);
}